rootProject.name = "Java-DesignPatterns"
include("abstract-factory")
include("builder")
include("factory")
include("prototype")
include("singleton")
include("adapter")
include("bridge")
include("composite")
include("decorator")
include("facade")
include("flyweight")
include("proxy")
include("strategy")
